#bouwt de docker images en gaat die ook runnen
    - name: remove geolatte-nosqlfs postgres
      action: shell docker rm -f geolatte-nosqlfs-postgres || true

    - name: remove geolatte-nosqlfs
      action: shell docker rm -f geolatte-nosqlfs || true

    - name: build images
      action: command docker build --no-cache={{no_cache}} -t geolatte-nosqlfs {{docker_dir}}

    - name: run geolatte-nosqlfs postgres
      action: command docker run -d --name="geolatte-nosqlfs-postgres" --hostname="nosqlfspostgres" -p 49032:5432 wegenenverkeer/postgres /sbin/my_init --enable-insecure-key

    - wait_for: port=49032 delay=10

    - shell: PGPASSWORD=docker psql -U docker -h 0.0.0.0 -p 49032 -d postgres --command "CREATE USER nosql WITH SUPERUSER PASSWORD 'nosql';"

    - shell: PGPASSWORD=docker createdb -U docker -h 0.0.0.0 -p 49032 -O nosql --template=template_postgis2.1 nosql

    - name: run geolatte-nosqlfs container
      action: command docker run -d --name="geolatte-nosqlfs" --hostname="geolatte-nosqlfs" --link geolatte-nosqlfs-postgres:db -p 49034:8080 geolatte-nosqlfs /sbin/my_init --enable-insecure-key

    - wait_for: port=49034 delay=10
