#restart de gedeployde service

    - name: restart locatieservices in container
      action: command ssh root@{{item}} -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i {{docker_dir}}/insecure_key sv restart locatieservices
      with_items: docker_ip.stdout
